name: build and deployment of five-a-side-api microservice

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the staging branch for testing purposes
  push:
    branches: [ staging ]

jobs:
  
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: five-a-side-api-stg
    steps:

    - name: Build - Checkout code
      uses: actions/checkout@v3

    - name: Build - Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Build - Static Analysis
      run: docker compose up lint
      env:
        CI: true

    - name: Build - Unit Tests
      run: docker compose run tests
      env:
        CI: true

    - name: Build - Integration Tests
      run: echo "Running Integration Tests"
      env:
        CI: true

  deploy:
    name: Deploy
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    runs-on: ubuntu-latest
    environment: five-a-side-api-stg
    needs: build
    steps:

      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only