name: Node.js CI/CD

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build and test
      run: npm run build && npm test
      env:
        CI: true

    - name: Build the image
      run: |
        docker build -f Dockerfile -t five-a-side-api:latest .

    - name: Push the image to Heroku Container Registry
      run: |
        heroku container:login
        heroku container:push development -a five-a-side-api-stg
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Release the image to the app
      run: |
        heroku container:release development -a five-a-side-api-stg
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}